### ISSUE TITLE
Bump version tag v2.0.0

### ISSUE THREAD

**Issue by HonzaMac** [marcbachmann/umzug-cli#10]
Hi, 
Is it possible to bump new version? I've seen, that on master there is new commit for v2.0.0

Thanks!

**Comment by marcbachmann** [comment]
Oh, sure. I only pushed to npm. The tag will be there in a few seconds.
![image](https://user-images.githubusercontent.com/431376/34106275-e2ce4440-e3f7-11e7-88c1-6fc86928786d.png)

**Comment by marcbachmann** [comment]
Done https://github.com/marcbachmann/umzug-cli/tree/v2.0.0

**Comment by HonzaMac** [comment]
Thanks!
